In [8]:
import pandas as pd

In [9]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')

In [10]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [12]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [13]:
###Drop Nan Values
df=df.dropna()

In [14]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [15]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [16]:
## Get the Dependent features
y=df['label']

In [17]:
X.shape

(18285, 4)

In [18]:
y.shape

(18285,)

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,Dense

In [21]:
### Vocabulary size just consider dictionary of words u can give any value
voc_size=5000

In [22]:
#Onehot Representation
messages=X.copy()
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [23]:
messages.reset_index(inplace=True)

In [24]:
import nltk
import re
from nltk.corpus import stopwords

In [25]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [26]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [28]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[786, 1793, 3815, 1023, 3868, 4622, 1814, 3428, 3191, 2742],
 [2216, 2281, 910, 290, 275, 3760, 2311],
 [4943, 2043, 591, 116],
 [1835, 4644, 3104, 1226, 2078, 4193],
 [3297, 275, 1754, 2738, 382, 2924, 275, 937, 2293, 3416],
 [3472,
  2361,
  255,
  1966,
  178,
  1920,
  2259,
  1753,
  574,
  248,
  4121,
  250,
  3925,
  2168,
  2311],
 [4521, 611, 1209, 300, 1208, 24, 1129, 3962, 3032, 412, 4117],
 [1106, 1413, 3994, 2165, 2911, 4137, 1920, 2950, 3032, 412, 4117],
 [2082, 3472, 4990, 773, 263, 4450, 582, 2377, 1920, 2226],
 [3845, 184, 3986, 2023, 3124, 2606, 4166, 3458],
 [2190, 1450, 3285, 2552, 3253, 4034, 4753, 1269, 2555, 4819, 342],
 [1226, 4529, 3868, 4450, 1920, 2911],
 [2788, 4036, 1788, 4225, 2149, 3927, 241, 326, 1406],
 [760, 527, 1045, 3180, 4968, 1628, 135, 3032, 412, 4117],
 [312, 581, 1112, 1805, 3438, 3032, 412, 4117],
 [4649, 3090, 4706, 2629, 2488, 2836, 3588, 525, 3067, 365],
 [1239, 279, 2281],
 [535, 1992, 4418, 3363, 1920, 2131, 1255, 2311],
 [2777, 3571, 9

In [29]:
#Embedding Representation
sent_length=20 #to make all the sen of equal shape
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3428 3191 2742]
 [   0    0    0 ...  275 3760 2311]
 [   0    0    0 ... 2043  591  116]
 ...
 [   0    0    0 ... 3032  412 4117]
 [   0    0    0 ... 3549  199 3327]
 [   0    0    0 ...  550  203 2162]]


In [30]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  786,
       1793, 3815, 1023, 3868, 4622, 1814, 3428, 3191, 2742], dtype=int32)

In [32]:
## Creating model
from tensorflow.keras.layers import Dropout
embedding_vector_features=40 # in embedding layer it takes input and converts some specific  no of features or vectors u can give any no
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100)) # one layer having 100 neurons
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [34]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [35]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [37]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 10s 39ms/step - loss: 0.4989 - accuracy: 0.7324 - val_loss: 0.1960 - val_accuracy: 0.9167
Epoch 2/10
192/192 [==============================] - 7s 36ms/step - loss: 0.1594 - accuracy: 0.9372 - val_loss: 0.1933 - val_accuracy: 0.9186
Epoch 3/10
192/192 [==============================] - 7s 37ms/step - loss: 0.1082 - accuracy: 0.9626 - val_loss: 0.2030 - val_accuracy: 0.9193
Epoch 4/10
192/192 [==============================] - 7s 37ms/step - loss: 0.0735 - accuracy: 0.9751 - val_loss: 0.2709 - val_accuracy: 0.9170
Epoch 5/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0425 - accuracy: 0.9827 - val_loss: 0.2640 - val_accuracy: 0.9062
Epoch 6/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0332 - accuracy: 0.9903 - val_loss: 0.3895 - val_accuracy: 0.9075
Epoch 7/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0195 - accuracy: 0.9941 - val_loss: 0.3752 - val_accuracy: 0.912

In [38]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3167,  252],
       [ 326, 2290]])

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9042253521126761